### ISSUE TITLE
o-grid not working with responsive prefixes

### ISSUE THREAD

**Issue by nelhop** [lnolte/und-css#39]
It seems that `o-grid` does not work with responsive prefixes like `lg:o-grid`.
If such a prefix (sm, md, lg) is present, no o-grid styles are applied.

**Comment by lnolte** [comment]
This is intended. The intended way to use it is to apply responsive prefixes to the child elements to set their size for a given breakpoint like `md:u-w-1/2`, `lg:u-w-1/4` and so on...

**Comment by nelhop** [comment]
agreed
